name: Alpha

on:
  push:
    branches-ignore:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          scope: "@ddd-ts"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - run: npm version 0.0.0-feat.${{ github.ref_name }}.${SHORT_SHA} --workspaces
      - run: npm publish --access public --workspaces --tag feat.${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
