name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  test:
    if: github.event_name != 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: ./.github/actions/setup

      - run: pnpm test

  audit:
    if: github.event_name != 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: ./.github/actions/setup

      - run: pnpm audit --audit-level=high

  release-main:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test, audit]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: ./.github/actions/setup

      - name: Release main
        run: sh .github/workflows/release-main.sh

  release-alpha:
    if: >-
      github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    environment: release-alpha
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/setup

      - name: Release alpha
        run: sh .github/workflows/release-alpha.sh
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
